#136 Add lockfile removal to avoid weird SQ states in cluster deployment
Sometimes this error message indicates why SonarQube gets stuck during
the start-up in a Kubernetes cluster. The node lock deletion is supposed
to counter this error.

java.lang.IllegalStateException: failed to obtain node locks, tried
 [/opt/sonar/data/es8]; maybe these locations are not writable or
  multiple nodes were started on the same data path?